/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DkZboSFf06B
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function BlogComponent() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="bg-background border-b">
        <div className="container flex items-center justify-between h-14 px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="sr-only">Blood Donation Center</span>
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Donate
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Volunteer
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Impact
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4 text-primary"
              prefetch={false}
            >
              Blog
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" size="sm" className="md:hidden">
            <MenuIcon className="h-5 w-5" />
            <span className="sr-only">Toggle menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-20 bg-background px-4 md:px-6">
          <div className="container">
            <h2 className="text-4xl font-bold">Blog</h2>
            <p className="mt-4 text-muted-foreground">
              Read the latest stories, updates, and educational content from the Blood Donation Center.
            </p>
            <div className="mt-8 grid md:grid-cols-3 gap-8">
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Blog Post 1"
                  width={200}
                  height={150}
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <div>
                  <h4 className="font-medium">The Importance of Blood Donation</h4>
                  <p className="text-muted-foreground">
                    Learn why donating blood is crucial and how it can save lives.
                  </p>
                  <Link href="#" className="text-primary" prefetch={false}>
                    Read More
                  </Link>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Blog Post 2"
                  width={200}
                  height={150}
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <div>
                  <h4 className="font-medium">Debunking Blood Donation Myths</h4>
                  <p className="text-muted-foreground">
                    Explore common misconceptions about blood donation and the facts.
                  </p>
                  <Link href="#" className="text-primary" prefetch={false}>
                    Read More
                  </Link>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Blog Post 3"
                  width={200}
                  height={150}
                  className="rounded-md"
                  style={{ aspectRatio: "200/150", objectFit: "cover" }}
                />
                <div>
                  <h4 className="font-medium">The Blood Donation Process Explained</h4>
                  <p className="text-muted-foreground">
                    Get a step-by-step guide on what to expect when donating blood.
                  </p>
                  <Link href="#" className="text-primary" prefetch={false}>
                    Read More
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-background py-6 border-t">
        <div className="container flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 Blood Donation Center. All rights reserved.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-sm text-muted-foreground hover:text-primary" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-primary" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-primary" prefetch={false}>
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
