/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Eo3n3UJLuIo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"

export function CreateBloodRequestComponent() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="bg-background border-b">
        <div className="container flex items-center justify-between h-14 px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="sr-only">Blood Donation Center</span>
          </Link>
          <h1 className="text-3xl font-bold text-primary">Create Blood Request</h1>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Donate
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Volunteer
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Impact
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Blog
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" size="sm" className="md:hidden">
            <MenuIcon className="h-5 w-5" />
            <span className="sr-only">Toggle menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-20 bg-background px-4 md:px-6">
          <div className="container">
            <form className="max-w-2xl mx-auto space-y-6">
              <div>
                <h2 className="text-2xl font-bold">Patient Information</h2>
                <div className="grid grid-cols-2 gap-6 mt-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" placeholder="Enter full name" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="dob">Date of Birth</Label>
                    <Input id="dob" type="date" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="gender">Gender</Label>
                    <Select id="gender">
                      <SelectTrigger>
                        <SelectValue placeholder="Select gender" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="male">Male</SelectItem>
                        <SelectItem value="female">Female</SelectItem>
                        <SelectItem value="other">Other</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="blood-type">Blood Type</Label>
                    <RadioGroup>
                      <RadioGroupItem value="a-positive" id="a-positive">
                        <Label htmlFor="a-positive">A+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="a-negative" id="a-negative">
                        <Label htmlFor="a-negative">A-</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="b-positive" id="b-positive">
                        <Label htmlFor="b-positive">B+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="b-negative" id="b-negative">
                        <Label htmlFor="b-negative">B-</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="ab-positive" id="ab-positive">
                        <Label htmlFor="ab-positive">AB+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="ab-negative" id="ab-negative">
                        <Label htmlFor="ab-negative">AB-</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="o-positive" id="o-positive">
                        <Label htmlFor="o-positive">O+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="o-negative" id="o-negative">
                        <Label htmlFor="o-negative">O-</Label>
                      </RadioGroupItem>
                    </RadioGroup>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="phone">Phone</Label>
                    <Input id="phone" type="tel" placeholder="Enter phone number" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input id="email" type="email" placeholder="Enter email" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="hospital">Hospital/Clinic</Label>
                    <Input id="hospital" placeholder="Enter hospital or clinic name" />
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-2xl font-bold">Blood Request Details</h2>
                <div className="grid grid-cols-2 gap-6 mt-4">
                  <div className="space-y-2">
                    <Label htmlFor="quantity">Quantity Needed</Label>
                    <Input id="quantity" type="number" placeholder="Enter quantity" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="blood-type-required">Blood Type Required</Label>
                    <RadioGroup>
                      <RadioGroupItem value="a-positive" id="a-positive-required">
                        <Label htmlFor="a-positive-required">A+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="a-negative" id="a-negative-required">
                        <Label htmlFor="a-negative-required">A-</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="b-positive" id="b-positive-required">
                        <Label htmlFor="b-positive-required">B+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="b-negative" id="b-negative-required">
                        <Label htmlFor="b-negative-required">B-</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="ab-positive" id="ab-positive-required">
                        <Label htmlFor="ab-positive-required">AB+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="ab-negative" id="ab-negative-required">
                        <Label htmlFor="ab-negative-required">AB-</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="o-positive" id="o-positive-required">
                        <Label htmlFor="o-positive-required">O+</Label>
                      </RadioGroupItem>
                      <RadioGroupItem value="o-negative" id="o-negative-required">
                        <Label htmlFor="o-negative-required">O-</Label>
                      </RadioGroupItem>
                    </RadioGroup>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="reason">Reason for Request</Label>
                    <Textarea id="reason" placeholder="Enter a brief explanation" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="urgent">Urgent Need</Label>
                    <Checkbox id="urgent" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="donation-center">Preferred Donation Center</Label>
                    <Input id="donation-center" placeholder="Enter preferred donation center" />
                  </div>
                </div>
              </div>
              <Button type="submit" className="w-full">
                Submit Request
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-background py-6 border-t">
        <div className="container flex items-center justify-between">
          <p className="text-sm text-muted-foreground">&copy; 2024 Blood Donation Center. All rights reserved.</p>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-sm text-muted-foreground hover:text-primary" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-primary" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-primary" prefetch={false}>
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
